# Site Settings
baseurl: ""
url : "https://tmfrl042.github.io/"

# Blog Settings
theme_settings :
  title : Seulki's Blog
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Seulki Kim
    description : Seulki Amanda Kim
    experience :
      - start : 2020-01-02
        end : ~
        experience : ~
    skills : 
      - skill : SQL(Oracle)
        value : 30  # Percent value
        
  # Icons
  icons :
    email: tmfrl042@naver.com # Full email address, e.g. "sample@google.com"
    linkedin: https://www.linkedin.com/in/tmfrl042/  # Full URL 
    github: https://github.com/tmfrl042
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
